services:
  api:
    environment:
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_SQS_INPUT_QUEUE_URL: ${AWS_SQS_INPUT_QUEUE_URL}
      AWS_SQS_OUTPUT_QUEUE_URL: ${AWS_SQS_OUTPUT_QUEUE_URL}
      AWS_SQS_DLQ_URL: ${AWS_SQS_DLQ_URL}
